import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

type LayoutInterface = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: LayoutInterface) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
